package au.edu.rmit.sept.webapp.service;

import org.springframework.web.multipart.MultipartFile;

import java.io.IOException;

/**
 * PhotoStorageService Interface
 * Abstraction for photo storage implementations (local filesystem or cloud storage).
 *
 * IMPLEMENTATIONS:
 * - LocalFileStorage (@Profile "dev", "devprod"): Stores photos in local filesystem
 * - GCSStorage (@Profile "prod"): Stores photos in Google Cloud Storage
 *
 * DESIGN:
 * - Filename is UUID-based (generated by implementation) to prevent path traversal
 * - Both original and thumbnail (300x300px) are stored
 * - URLs returned are ready for direct use in HTML (img src)
 */
public interface PhotoStorageService {

    /**
     * Uploads a photo file and generates a thumbnail.
     * Stores both original and thumbnail versions.
     *
     * @param eventId The event ID (used for directory/path structure)
     * @param file The uploaded file
     * @param originalFilename The original filename from user upload
     * @return The generated UUID-based filename (e.g., "abc123-def456.jpg")
     * @throws IOException If file storage fails
     * @throws IllegalArgumentException If file type or size is invalid
     */
    String uploadPhoto(Long eventId, MultipartFile file, String originalFilename) throws IOException;

    /**
     * Deletes both the original photo and its thumbnail from storage.
     *
     * @param eventId The event ID
     * @param filename The UUID-based filename
     * @throws IOException If deletion fails
     */
    void deletePhoto(Long eventId, String filename) throws IOException;

    /**
     * Gets the URL for the original (full-size) photo.
     *
     * @param eventId The event ID
     * @param filename The UUID-based filename
     * @return URL for accessing the original photo
     */
    String getPhotoUrl(Long eventId, String filename);

    /**
     * Gets the URL for the thumbnail photo.
     *
     * @param eventId The event ID
     * @param filename The UUID-based filename
     * @return URL for accessing the thumbnail photo
     */
    String getThumbnailUrl(Long eventId, String filename);

    /**
     * Downloads a photo file as a byte array for proxied download.
     *
     * @param eventId The event ID
     * @param filename The UUID-based filename
     * @return The photo file content as byte array
     * @throws IOException If file retrieval fails
     */
    byte[] downloadPhoto(Long eventId, String filename) throws IOException;
}
